# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           /:title

# Setup
title:               jjingK
tagline:             "'s blog"
description:         'Made by <a href="https://github.com/jjingK" target="_blank">@jjingK</a>.'
url:                 https://jjingk.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Hye Jin
  url:               https://github.com/jjingK
  email:             likelamb7@gmail.com

# Custom vars
version:             1.0.0
