# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Not yet
tagline: "programmer"
email: likelamb7@gmail.com
description: 'Made by <a href="https://github.com/jjingK" target="_blank">@jjingK</a>.'
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://jjingk.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /:title
paginate: 1

# About/contact
author:
  name:              Hye Jin
  url:               https://github.com/jjingK
  email:             likelamb7@gmail.com

# Custom vars
version:             1.0.0

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
